services:
  - type: web
    name: delta-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn Backend.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: false
